name: 🤖 Auto Review Pull Request

# Khi nào workflow này chạy
on:
  pull_request:
    types: [opened, synchronize, reopened]
    # Chỉ chạy cho AI code reviewer (tránh loop)
    paths:
      - "ai-code-reviewer/**"

# Quyền cần thiết cho workflow
permissions:
  contents: read
  pull-requests: write
  checks: read
  issues: write

jobs:
  auto-review:
    name: 🤖 AI Code Review
    runs-on: ubuntu-latest

    # Chỉ chạy nếu không phải bot tạo PR (tránh infinite loop)
    if: github.actor != 'github-actions[bot]'

    steps:
      # 1. Checkout code từ repository
      - name: 📦 Checkout repository
        uses: actions/checkout@v4
        with:
          # Lấy toàn bộ history để so sánh changes
          fetch-depth: 0

      # 2. Setup Node.js environment
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "ai-code-reviewer/package-lock.json"

      # 3. Install dependencies
      - name: 📥 Install dependencies
        working-directory: ./ai-code-reviewer
        run: npm ci

      # 4. Run auto-review
      - name: 🤖 Run AI Auto Review
        working-directory: ./ai-code-reviewer
        env:
          # GitHub tự động cung cấp GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # API keys từ repository secrets
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          # GitHub Actions context
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: npm run auto-review-action

      # 5. Upload logs nếu có lỗi (for debugging)
      - name: 📋 Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: auto-review-logs
          path: ai-code-reviewer/logs/
          retention-days: 7
